# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14dNKpPuDWWjVag1kTNWF6-wl9QgngRu-

##Practical 1 - To study and implement numpy library

Importing numpy
"""

import numpy as np
print(np.__version__)

"""converting the list into array using the numpy functions printing different elements and operations on the elements of the array

"""

arr = np.array([1,2,3,4])
print(arr[0])
print(arr[2] + arr[3])

"""printing specific elements of the array using indexing

"""

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

"""using dtype to get the type of elements in the array

"""

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])
print(arr[:4])

import numpy as np
ar = np.array([1,2,3,4])
print(arr.dtype)

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

import numpy as np
arr = np.array(['apple','banana','cherry'])
print(arr.dtype)




arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.shape)

arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array:',arr.shape)

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

"""using ndim to get the specific type of dimensions in the array

"""

import numpy as np
a= np.array([(1,2,3),(3,4,4)])
print (a)
print(type(a))
b=np.array([1,2,3])
print(b)
print(b.dtype)
print(a.ndim)
print(b.ndim)
print(a.shape)
print(a.shape)
a.dtype

a=np.array([(1,2,3),(3,4,4)],dtype='int16')
print(a.dtype)
print(a.itemsize)

"""itemsize returns type of individual element in the array which is 16bits = 2 bytes
ndtype is used to give a specific datatype to the elements in the array
size gives the total number of elements in the array (2rows*3columns) = 6

"""

a=np.array([(1,2,3),(3,4,4)], dtype='int32')
print(a.itemsize)
print(a.size)
print(a.size *a.itemsize)
print(a.nbytes)

"""arrange gives a specific range of elemnts by taking the starting index, end index and stepping point

"""

#accesing changing specific elements,rows,columns,etc.
w=np.arange(start=1, stop=10, step=2)
print(w)
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)
print(a[1,4])
a[0,-1]
print(a[1, :])
print(a[:,5])
print(a[0,1:6:2])
a[1,6]=20
print(a)
a[:, 2]=5
print(a)
a[:,2]=1,2
print(a)

#3D array
q=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(q)
print(q[0,1,1])
print(q[:,1,:])

import numpy as np
a = np.array([(1,2,3),(3,4,4)])
print(a)
print(type(a))

b = np.array([1,2,3])
print(b)

print(b.dtype)#tells us the data types of the elements in the array

#get dimensions(number of dimensions)
print(a.ndim)
print(b.ndim)

#get shape
print(a.shape)#ndim and shape are properties of an array
print(b.shape)

a.dtype

a = np.array([(1,2,3),(3,4,4)],dtype = 'int16')
print(a.dtype)

#get item size on bytes
print(a.itemsize)

#if i increase the dtype size to int32, i will get itemsize as 4
a = np.array([(1,2,3),(3,4,4)],dtype = 'int32')
print(a.itemsize) #no. of items, exp 32 bytes = 4 bits
print(a.size) #no of elements in the array

#get the total size or number of bytes
print(a.size*a.itemsize)
print(a.nbytes) #the above print statement is the explaination

w = np.arange(start = 1, stop = 10, step = 2)
print(w)

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

#accessing a specific element[row,col]
print(a[1,4])
a[0,-1]

#accessing a complete row or column
print(a[1, :])
print(a[:,5])

#change value
a[1,6] = 20
print(a)

#to change a series of numbers
a[:,2]=5
print(a)

a[:,2] =1,2
print(a)

#3D array
q = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(q)

print(q[0,1,1])
print(q[:,1,:])#from both matrix, 2nd row and then elements

#replace
q[:,1,:] = [9,9],[9,9]
q

#creating a matrix with all zero element
a = np.zeros((2,2))
print(a)

print(np.zeros((2,2,3)))

#all 1's matrix
print(np.ones((4,2,2), dtype = 'int32'))

#a matix of your choice
print(np.full((2,2),99, dtype = 'float32'))

#reusing preivious matrix
print(np.full_like(q,7))

#creating random numbers
print(np.random.rand(2,3))
print(np.random.random_sample(q.shape))

#generate matrix of random numbers
print(np.random.randint(7, size = (3,3)))
print(np.random.randint(-6,6, size = (2,2)))
print(np.random.randint(-6,6,2))
print(np.identity(7, dtype='int16'))

#copying array
a=np.array([1,2,3])
b = a #a is created and then b is also pointing to the same object, a copy is not getting created , its the same object.
print(b)

b[0] = 100
print(b)
print(a)


b = a.copy()
print(a)
b[2] = 90
print(b)
print(a)

#mathematics/braodcasting
a = np.array([1,2,3,4])
print(a)

a+=2

print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)

b = np.array([1,0,1,0])
print(a+b)

print(a**2)

print(np.sin(a))
print(np.cos(a))

a=np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

#matrix multiplication: output would be 2 by 2 matrix
print(np.matmul(a,b))

#find the determinant of a mtrix
c = np.identity(3)
print(np.linalg.det(c))

"""#Statistics"""

stats = np.array([[5,2,3],[4,5,6]])
stats
print(np.max(stats, axis = 1)) #it returns the new array with max values from each row
print(np.max(stats, axis = 0)) #it returns the new array with max values from each column
print(np.min(stats))
print(np.sum(stats))
sum(sum(stats))